### ISSUE TITLE
Cuenta con varias áreas - Sólo funciona primer pedido

### ISSUE THREAD

**Issue by aruizfpsanjorge** [AdminIKT/CSJ#31]
En las cuentas que hay varias áreas asignadas, deja hacer un primer pedido, y al intentar hacer otro pedido casca, o al intentar hacer un cobro por factura del primero también.
PRY-L-EUSKELEC/22-1 description not matches with @(^[\w]+)-(E|F|L|O)-?([\d]*)/([\d]{2})-([\d|-]+)@ pattern

**Comment by AdminIKT** [comment]
Creo que se debe a que el código del pedido lleva caracteres no numericos y no coincide con el patrón de pedido.
He cambiado el patrón para que acepte letras: @(^[\w]+)-(E|F|L|O)-?([\**w**]*)/([\d]{2})-([\d|-]+)@
