### ISSUE TITLE
Cobro a cuenta

### ISSUE THREAD

**Issue by ItUrri** [AdminIKT/CSJ#47]
En caso de que la cuenta tenga más de un área, ¿a cuál de ellas se debería aplicar el cargo?

**Comment by aruizfpsanjorge** [comment]
Buena pregunta....

**Comment by aruizfpsanjorge** [comment]
Si es una cuenta con un sólo área ponemos el acrónimo de la cuenta
C#PM-F xxxxxxxxxxx

Si es una cuenta con varias áreas, añadimos el acrónimo del área donde cargamos:
C#PM-F/MAT xxxxxxxxxxxxxx
C#PM-F/MRK xxxxxxxxxxxxxx
